#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : capstone
Version  : 4.0.2
Release  : 2
URL      : https://github.com/aquynh/capstone/archive/4.0.2/capstone-4.0.2.tar.gz
Source0  : https://github.com/aquynh/capstone/archive/4.0.2/capstone-4.0.2.tar.gz
Summary  : A lightweight multi-platform, multi-architecture disassembly framework
Group    : Development/Tools
License  : BSD-3-Clause NCSA
Requires: capstone-bin = %{version}-%{release}
Requires: capstone-lib = %{version}-%{release}
Requires: capstone-license = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : buildreq-distutils3

%description
Capstone is a disassembly framework with the target of becoming the ultimate
disasm engine for binary analysis and reversing in the security community.

%package bin
Summary: bin components for the capstone package.
Group: Binaries
Requires: capstone-license = %{version}-%{release}

%description bin
bin components for the capstone package.


%package dev
Summary: dev components for the capstone package.
Group: Development
Requires: capstone-lib = %{version}-%{release}
Requires: capstone-bin = %{version}-%{release}
Provides: capstone-devel = %{version}-%{release}
Requires: capstone = %{version}-%{release}

%description dev
dev components for the capstone package.


%package lib
Summary: lib components for the capstone package.
Group: Libraries
Requires: capstone-license = %{version}-%{release}

%description lib
lib components for the capstone package.


%package license
Summary: license components for the capstone package.
Group: Default

%description license
license components for the capstone package.


%prep
%setup -q -n capstone-4.0.2
cd %{_builddir}/capstone-4.0.2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1589208176
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%cmake ..
make  %{?_smp_mflags}  VERBOSE=1
popd

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
cd clr-build; make test

%install
export SOURCE_DATE_EPOCH=1589208176
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/capstone
cp %{_builddir}/capstone-4.0.2/LICENSE.TXT %{buildroot}/usr/share/package-licenses/capstone/861af24907e399e873920dbbff1ea1dd73a9ba35
cp %{_builddir}/capstone-4.0.2/LICENSE_LLVM.TXT %{buildroot}/usr/share/package-licenses/capstone/afc034c0ae47cbd47a99c6c5992d846511bb33ad
cp %{_builddir}/capstone-4.0.2/bindings/python/LICENSE.TXT %{buildroot}/usr/share/package-licenses/capstone/861af24907e399e873920dbbff1ea1dd73a9ba35
cp %{_builddir}/capstone-4.0.2/suite/regress/LICENSE %{buildroot}/usr/share/package-licenses/capstone/7de9d56eea42f5bbbba6fff880d912f2c9c3a45d
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/cstool

%files dev
%defattr(-,root,root,-)
/usr/include/capstone/arm.h
/usr/include/capstone/arm64.h
/usr/include/capstone/capstone.h
/usr/include/capstone/evm.h
/usr/include/capstone/m680x.h
/usr/include/capstone/m68k.h
/usr/include/capstone/mips.h
/usr/include/capstone/platform.h
/usr/include/capstone/ppc.h
/usr/include/capstone/sparc.h
/usr/include/capstone/systemz.h
/usr/include/capstone/tms320c64x.h
/usr/include/capstone/x86.h
/usr/include/capstone/xcore.h
/usr/lib64/libcapstone.so
/usr/lib64/pkgconfig/capstone.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libcapstone.so.4
/usr/lib64/libcapstone.so.4.0.2

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/capstone/7de9d56eea42f5bbbba6fff880d912f2c9c3a45d
/usr/share/package-licenses/capstone/861af24907e399e873920dbbff1ea1dd73a9ba35
/usr/share/package-licenses/capstone/afc034c0ae47cbd47a99c6c5992d846511bb33ad
